### ISSUE TITLE
What is the difference between this repo and gatsby-theme-carbon

### ISSUE THREAD

**Issue by awkale** [carbon-design-system/gatsby-starter-carbon-theme#7]
I can't figure out how this repo differs from https://github.com/carbon-design-system/gatsby-theme-carbon 
Does anyone know?

**Comment by alexanderbartels** [comment]
@awkale this is a boilerplate, so you have some example content. Its handy to have a starting point to use the theme. The Gatsby Theme is located at https://github.com/carbon-design-system/gatsby-theme-carbon

**Comment by joshblack** [comment]
To echo what @alexanderbartels shared above, this is the starter for the theme that folks can use with Gatsby's `new` command. For example:

```bash
npx gatsby new my-project https://github.com/carbon-design-system/gatsby-starter-carbon-theme
```

Thanks for helping out here, @alexanderbartels! Going to close this out, let us know if you have any more questions 😄
